import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { chmod, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/**
 * Bridge personal fish functions/aliases/abbreviations (gs, la, fmt, ...) into
 * pi's `!`/`!!` shell commands, which run under non-interactive /bin/bash.
 *
 * On every session start this regenerates one tiny shim executable per
 * user-defined name into ~/.config/pi/fish-shims. The `shellCommandPrefix`
 * setting puts that dir on PATH for every bash execution. Only names bash
 * cannot already resolve get a shim, so real commands and builtins (cd, grep,
 * ls, kill, ...) are never shadowed and the model's bash tool keeps working.
 *
 * Each shim runs `fish -ic '<invocation> $argv'`, i.e. INTERACTIVE fish. That
 * matters: the user's aliases (ls->eza, cat->bat) live in conf.d/aliases.fish
 * behind a `status is-interactive` guard, so a non-interactive `fish -c 'la'`
 * would silently fall back to fish's embedded default `la`. Interactive fish
 * runs fine without a tty here (stdin redirected), emits no greeting noise, and
 * exits cleanly.
 *
 * Three kinds of user names are captured:
 *   - autoload function files in ~/.config/fish/functions/*.fish (gs, kp, ...)
 *   - functions/aliases that shadow a fish embedded default with a DIFFERENT
 *     body (la, ll, lt) - detected by diffing bodies with vs without config,
 *     so pristine fish builtins the user never touched stay excluded
 *   - simple abbreviations (fmt, lg, zj, sshh, ...) - shimmed to their
 *     expansion; interactive-only/harmful ones (cd, exec, clear) are skipped
 *
 * Why not shellPath=fish: it also drives the model's bash tool, and fish cannot
 * run bash syntax (heredocs, [[ ]], for loops). Why not
 * command_not_found_handle: macOS ships bash 3.2, which lacks it.
 */

const run = promisify(execFile);

const SHIM_DIR = join(homedir(), ".config/pi/fish-shims");
const FUNC_DIR = join(homedir(), ".config/fish/functions");
const VALID_NAME = /^[A-Za-z][A-Za-z0-9_-]*$/;
const BODY_MARKER = "@@FISHSHIM@@:";
// Directory listers that print nothing with no path operand when stdout/stdin
// is not a tty (eza v0.23+ issue #1725). Their bare aliases (la, ll, lt) must
// default to "." so `la` with no args still lists the cwd under pi's bash.
const LISTERS = new Set(["eza", "exa", "ls", "gls", "lsd", "tree"]);

type Shim = { invocation: string; cwdDefault: boolean };

export default function (pi: ExtensionAPI) {
  pi.on("session_start", async () => {
    try {
      await regenerateShims();
    } catch {
      // Shim regeneration is best-effort; never block or break the session.
    }
  });
}

export async function regenerateShims(): Promise<void> {
  const fish = await findFish();
  if (!fish) return;

  const candidates = await collectCandidates(fish);
  const shimNames = await excludeBashResolvable([...candidates.keys()]);

  await mkdir(SHIM_DIR, { recursive: true });
  for (const stale of await readdir(SHIM_DIR)) {
    await rm(join(SHIM_DIR, stale), { force: true });
  }

  for (const name of shimNames) {
    const { invocation, cwdDefault } = candidates.get(name)!;
    const shimPath = join(SHIM_DIR, name);
    const inv = shSingleQuote(`${invocation} $argv`);
    const lines = [
      "#!/bin/sh",
      "# Generated by the fish-shims pi extension. Do not edit.",
    ];
    // Non-tty listers (eza et al.) print nothing without a path operand, so
    // fall back to the current directory when invoked with no arguments.
    if (cwdDefault) lines.push('[ "$#" -eq 0 ] && set -- .');
    lines.push(`exec '${fish}' -ic ${inv} -- "$@"`, "");
    await writeFile(shimPath, lines.join("\n"));
    await chmod(shimPath, 0o755);
  }
}

async function findFish(): Promise<string | null> {
  if (existsSync("/opt/homebrew/bin/fish")) return "/opt/homebrew/bin/fish";
  try {
    const { stdout } = await run("/usr/bin/which", ["fish"]);
    const found = stdout.trim().split("\n")[0];
    return found || null;
  } catch {
    return null;
  }
}

/**
 * Build a map of name -> invocation for every user-defined shortcut. The
 * invocation is the name itself for functions/aliases, or the expansion text
 * for abbreviations.
 */
async function collectCandidates(fish: string): Promise<Map<string, Shim>> {
  const [withConfig, bare, autoloadFiles, abbrs] = await Promise.all([
    listBodies(fish, ["-i"]),
    listBodies(fish, ["--no-config"]),
    readdir(FUNC_DIR).catch(() => [] as string[]),
    listAbbreviations(fish),
  ]);

  const out = new Map<string, Shim>();

  // Functions/aliases: keep a name only if it is not a pristine fish default,
  // i.e. it is absent from the bare shell OR the user gave it a different body.
  for (const [name, body] of withConfig) {
    const bareBody = bare.get(name);
    if (bareBody === undefined || bareBody !== body) {
      out.set(name, { invocation: name, cwdDefault: isBareLister(body) });
    }
  }

  // Autoload function files are always user-defined.
  for (const file of autoloadFiles) {
    if (file.endsWith(".fish")) {
      const name = file.slice(0, -".fish".length);
      const body = withConfig.get(name) ?? "";
      out.set(name, { invocation: name, cwdDefault: isBareLister(body) });
    }
  }

  // Abbreviations expand to their text; do not override a real function.
  for (const [name, expansion] of abbrs) {
    if (!out.has(name)) {
      out.set(name, {
        invocation: expansion,
        cwdDefault: isBareLister(expansion),
      });
    }
  }

  for (const name of [...out.keys()]) {
    if (
      !VALID_NAME.test(name) ||
      name.startsWith("_") ||
      name.startsWith("fish")
    ) {
      out.delete(name);
    }
  }

  return out;
}

/**
 * True when a body is a single directory-listing command with only flag
 * operands (e.g. `eza -la --icons --git`), so appending a path is safe and the
 * bare form should default to the current directory. Anything with a pipe,
 * chaining, or an explicit path argument is excluded.
 */
/**
 * Reduce a `functions -- name` dump to the inner command body: drop comment
 * lines, unwrap the `function ... end` frame, and dedent. This gives a stable
 * value to diff against fish's embedded default and to inspect for listers.
 */
function normalizeBody(rawLines: string[]): string {
  let lines = rawLines.filter((line) => !/^\s*#/.test(line));
  while (lines.length && lines[0].trim() === "") lines.shift();
  while (lines.length && lines[lines.length - 1].trim() === "") lines.pop();
  const first = lines[0]?.trim() ?? "";
  const last = lines[lines.length - 1]?.trim() ?? "";
  if (/^function\b/.test(first) && last === "end") {
    lines = lines.slice(1, -1);
  }
  return lines
    .map((line) => line.trim())
    .join("\n")
    .trim();
}

function isBareLister(body: string): boolean {
  const line = body.trim();
  if (!line || /[|;&(){}<>]/.test(line)) return false;
  const tokens = line.split(/\s+/);
  let cmd = tokens.shift();
  if (cmd === "command" || cmd === "builtin") cmd = tokens.shift();
  if (!cmd) return false;
  const base = cmd.split("/").pop()!;
  if (!LISTERS.has(base)) return false;
  // Every remaining operand must be a flag; an explicit path means no default.
  return tokens.every((token) => token.startsWith("-") || token === "$argv");
}

/**
 * Map every currently-known function name to a normalized (comment-stripped)
 * body. The with-config pass runs interactive fish (`-i`) so aliases behind a
 * `status is-interactive` guard (ls->eza, cat->bat) show their real bodies
 * instead of fish's embedded defaults.
 */
async function listBodies(
  fish: string,
  flags: string[],
): Promise<Map<string, string>> {
  const script = `for f in (functions -n); echo '${BODY_MARKER}'$f; functions -- $f; end`;
  const { stdout } = await run(fish, [...flags, "-c", script], {
    maxBuffer: 16 * 1024 * 1024,
  });

  const bodies = new Map<string, string>();
  let current: string | null = null;
  let lines: string[] = [];
  const flush = () => {
    if (current !== null) bodies.set(current, normalizeBody(lines));
  };

  for (const line of stdout.split("\n")) {
    if (line.startsWith(BODY_MARKER)) {
      flush();
      current = line.slice(BODY_MARKER.length);
      lines = [];
    } else {
      lines.push(line);
    }
  }
  flush();
  return bodies;
}

/**
 * Parse `abbr --show` into name -> expansion for plain command abbreviations.
 * Skips regex/function abbreviations and interactive-only or destructive ones
 * (cd, exec, clear) that make no sense as a one-shot bash command.
 */
async function listAbbreviations(fish: string): Promise<Map<string, string>> {
  const abbrs = new Map<string, string>();
  try {
    const { stdout } = await run(fish, ["-ic", "abbr --show"]);
    for (const line of stdout.split("\n")) {
      // Only the simple form: abbr -a -- NAME EXPANSION
      const match = line.match(/^abbr -a -- (\S+) (.+)$/);
      if (!match) continue;
      const name = match[1];
      const expansion = unquoteFish(match[2].trim());
      if (/(^|\s)(cd|exec)\s|(^|\s)clear($|\s|&|;)/.test(` ${expansion} `)) {
        continue;
      }
      abbrs.set(name, expansion);
    }
  } catch {
    // best-effort
  }
  return abbrs;
}

/** Strip one layer of surrounding fish single quotes if present. */
function unquoteFish(value: string): string {
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1).replace(/\\'/g, "'");
  }
  return value;
}

/** Quote a string as a single-quoted POSIX sh literal. */
function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/**
 * Drop every name bash can already resolve (binaries, builtins, keywords). The
 * probe runs with SHIM_DIR removed from PATH so our own generated shims never
 * count as "resolvable" and shadow-cancel themselves on regeneration.
 */
async function excludeBashResolvable(names: string[]): Promise<string[]> {
  if (names.length === 0) return [];
  const probe = names
    .map((name) => `command -v -- '${name}' >/dev/null 2>&1 && echo '${name}'`)
    .join("\n");
  const cleanPath = (process.env.PATH ?? "")
    .split(":")
    .filter((entry) => entry !== SHIM_DIR)
    .join(":");
  const { stdout } = await run("/bin/bash", ["-c", `${probe}\ntrue`], {
    env: { ...process.env, PATH: cleanPath },
  });
  const resolvable = new Set(stdout.split("\n").filter(Boolean));
  return names.filter((name) => !resolvable.has(name));
}
