import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { chmod, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/**
 * Bridge personal fish functions/aliases (gs, ga, ...) into pi's `!`/`!!`
 * shell commands, which run under non-interactive /bin/bash.
 *
 * On every session start this regenerates one tiny shim executable per
 * user-defined fish function into ~/.config/pi/fish-shims. The
 * `shellCommandPrefix` setting puts that dir on PATH for every bash
 * execution. Only names bash cannot already resolve get a shim, so real
 * commands and builtins (cd, grep, kill, ...) are never shadowed and the
 * model's bash tool keeps working untouched.
 *
 * Why not shellPath=fish: it also drives the model's bash tool, and fish
 * cannot run bash syntax (heredocs, [[ ]], for loops). Why not
 * command_not_found_handle: macOS ships bash 3.2, which lacks it.
 */

const run = promisify(execFile);

const SHIM_DIR = join(homedir(), ".config/pi/fish-shims");
const FUNC_DIR = join(homedir(), ".config/fish/functions");
const VALID_NAME = /^[A-Za-z][A-Za-z0-9_-]*$/;

export default function (pi: ExtensionAPI) {
  pi.on("session_start", async () => {
    try {
      await regenerateShims();
    } catch {
      // Shim regeneration is best-effort; never block or break the session.
    }
  });
}

export async function regenerateShims(): Promise<void> {
  const fish = await findFish();
  if (!fish) return;

  const candidates = await collectCandidates(fish);
  const shimNames = await excludeBashResolvable(candidates);

  await mkdir(SHIM_DIR, { recursive: true });
  for (const stale of await readdir(SHIM_DIR)) {
    await rm(join(SHIM_DIR, stale), { force: true });
  }

  for (const name of shimNames) {
    const shimPath = join(SHIM_DIR, name);
    const script = [
      "#!/bin/sh",
      "# Generated by the fish-shims pi extension. Do not edit.",
      `exec '${fish}' -c '${name} $argv' -- "$@"`,
      "",
    ].join("\n");
    await writeFile(shimPath, script);
    await chmod(shimPath, 0o755);
  }
}

async function findFish(): Promise<string | null> {
  if (existsSync("/opt/homebrew/bin/fish")) return "/opt/homebrew/bin/fish";
  try {
    const { stdout } = await run("/usr/bin/which", ["fish"]);
    const found = stdout.trim().split("\n")[0];
    return found || null;
  } catch {
    return null;
  }
}

/**
 * User-defined fish functions: everything fish knows with configs loaded
 * minus what a bare fish knows, plus autoloadable function files.
 */
async function collectCandidates(fish: string): Promise<string[]> {
  const [withConfig, bare, autoloadFiles] = await Promise.all([
    listFunctions(fish, []),
    listFunctions(fish, ["--no-config"]),
    readdir(FUNC_DIR).catch(() => [] as string[]),
  ]);

  const names = new Set(withConfig);
  for (const builtin of bare) names.delete(builtin);
  for (const file of autoloadFiles) {
    if (file.endsWith(".fish")) names.add(file.slice(0, -".fish".length));
  }

  return [...names].filter(
    (name) =>
      VALID_NAME.test(name) &&
      !name.startsWith("_") &&
      !name.startsWith("fish"),
  );
}

async function listFunctions(fish: string, flags: string[]): Promise<string[]> {
  const { stdout } = await run(fish, [...flags, "-c", "functions -n"]);
  return stdout.split(/[,\s]+/).filter(Boolean);
}

/** Drop every name bash can already resolve (binaries, builtins, keywords). */
async function excludeBashResolvable(names: string[]): Promise<string[]> {
  if (names.length === 0) return [];
  const probe = names
    .map((name) => `command -v -- '${name}' >/dev/null 2>&1 && echo '${name}'`)
    .join("\n");
  const { stdout } = await run("/bin/bash", ["-c", `${probe}\ntrue`]);
  const resolvable = new Set(stdout.split("\n").filter(Boolean));
  return names.filter((name) => !resolvable.has(name));
}
