#!/usr/bin/env bash
# ~/.config/pi/generate-fish-shims.sh
# Purpose: Make personal fish functions/aliases (gs, ga, ...) usable from Pi's
#   `!`/`!!` shell commands, which run under non-interactive /bin/bash.
#
#   macOS ships bash 3.2 (no command_not_found_handle) and Homebrew here is not
#   writable by this user, so instead of switching Pi's shellPath to fish
#   (which would break the model's bash-syntax commands: heredocs, [[ ]], for
#   loops), we generate one tiny shim executable per user-defined fish function
#   into ~/.config/pi/fish-shims. Pi puts that dir on PATH for every bash
#   execution via the `shellCommandPrefix` setting.
#
#   Safety rule: only names that bash CANNOT already resolve get a shim, so
#   wrappers of real commands/builtins (cd, grep, kill, cat, ...) are never
#   shadowed and the model's bash tool keeps working untouched.
#
#   The shims dir is generated output and gitignored. Re-run this script after
#   adding new fish functions/aliases (install-pi-config.sh runs it too).
# Usage: bash ~/.config/pi/generate-fish-shims.sh

set -euo pipefail

FISH="$(command -v fish || echo /opt/homebrew/bin/fish)"
SHIM_DIR="$HOME/.config/pi/fish-shims"
FUNC_DIR="$HOME/.config/fish/functions"

if [[ ! -x "$FISH" ]]; then
  echo "error: fish not found" >&2
  exit 1
fi

# Collect candidate names:
# 1. user-defined functions = (functions with config) - (functions in bare fish)
# 2. autoloadable function files in ~/.config/fish/functions
candidates="$(
  {
    comm -23 \
      <("$FISH" -c 'functions -n' | tr ', ' '\n' | LC_ALL=C sort -u) \
      <("$FISH" --no-config -c 'functions -n' | tr ', ' '\n' | LC_ALL=C sort -u)
    for f in "$FUNC_DIR"/*.fish; do
      [[ -e "$f" ]] || continue
      basename "$f" .fish
    done
  } | LC_ALL=C sort -u
)"

mkdir -p "$SHIM_DIR"
rm -f "$SHIM_DIR"/*

count=0
while IFS= read -r name; do
  [[ -n "$name" ]] || continue
  # Skip private/internal and oddly named functions.
  [[ "$name" == _* || "$name" == fish* ]] && continue
  [[ "$name" =~ ^[A-Za-z][A-Za-z0-9_-]*$ ]] || continue
  # Never shadow anything bash can already resolve (binaries, builtins, keywords).
  if /bin/bash -c "command -v -- '$name'" >/dev/null 2>&1; then
    continue
  fi
  {
    printf '#!/bin/sh\n'
    printf '# Generated by generate-fish-shims.sh. Do not edit.\n'
    printf 'exec %q -c %q -- "$@"\n' "$FISH" "$name \$argv"
  } > "$SHIM_DIR/$name"
  chmod +x "$SHIM_DIR/$name"
  count=$((count + 1))
done <<< "$candidates"

echo "generated $count fish shims in $SHIM_DIR"
